[package]
name = "vdf"
description = "VDF types and hash helpers for DOLI"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
crypto = { workspace = true }
thiserror.workspace = true
serde.workspace = true
hex.workspace = true

[dev-dependencies]
serde_json.workspace = true
